export const jobData = [
  {
    jobTitle: "Motion Graphics Designer",
    company: "Xapo Visuals",
    companyLogo: "https://i.imgur.com/9QXh1FZ.png",
    skills: ["Photoshop", "After Effects", "Blender", "Illustrator", "Figma"],
    duration: "3 months",
    stipend: "Rs. 10,000",
    applicants: "123",
    endsBy: "2023-07-27",
  },
  {
    jobTitle: "Frontend Developer",
    company: "TechCo Solutions",
    companyLogo: "https://i.imgur.com/5jOJqU9.png",
    skills: ["HTML", "CSS", "JavaScript", "React", "Redux"],
    duration: "6 months",
    stipend: "Rs. 15,000",
    applicants: "87",
    endsBy: "2023-08-15",
  },
  {
    jobTitle: "Marketing Intern",
    company: "Digital Marketing Agency",
    companyLogo: "https://i.imgur.com/2uKYsMx.png",
    skills: ["SEO", "Google Analytics"],
    duration: "2 months",
    stipend: "Rs. 8,000",
    applicants: "45",
    endsBy: "2023-09-10",
  },
  {
    jobTitle: "Data Analyst",
    company: "Analytics Inc.",
    companyLogo: "https://i.imgur.com/8L37U3r.png",
    skills: ["SQL", "Python", "Data Visualization", "Statistical Analysis"],
    duration: "4 months",
    stipend: "Rs. 12,000",
    applicants: "65",
    endsBy: "2023-10-05",
  },
  {
    jobTitle: "UI/UX Designer",
    company: "Creative Studio",
    companyLogo: "https://i.imgur.com/jFjoxHc.png",
    skills: [
      "User Research",
      "Wireframing",
      "Prototyping",
      "Usability Testing",
    ],
    duration: "3 months",
    stipend: "Rs. 9,000",
    applicants: "54",
    endsBy: "2023-11-21",
  },
  {
    jobTitle: "Backend Developer",
    company: "Tech Innovators",
    companyLogo: "https://i.imgur.com/Qf3SQiw.png",
    skills: ["Java", "Spring Boot", "MySQL", "RESTful APIs"],
    duration: "6 months",
    stipend: "Rs. 14,000",
    applicants: "78",
    endsBy: "2023-12-15",
  },
];
